# This workflow will upload a Python Package to PyPI when a version bump is detected in pyproject.toml
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Publish AlwaysOnTop Tooltip

on:
  push:
    paths:
      # Trigger only when py/toml-files are pushed in the alwaysontop_tooltip directory
      - 'alwaysontop_tooltip/**/*.py'
      - 'alwaysontop_tooltip/**/*.toml'

permissions:
  contents: read
  id-token: write

jobs:
  call-publish:
    uses: ./.github/workflows/Publish_to_PyPI_workflow.yml
    with:
      package-name: alwaysontop_tooltip
