# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Publish DynamicInputBox

on:
  push:
    paths:
      - 'dynamicinputbox/**'  # Triggers only when files are pushed/updated in the dynamicinputbox directory

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package from subfolder
        working-directory: ./dynamicinputbox
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dynamicinputbox/dist
